### ISSUE TITLE
Can not find connector-cryptolaemus and connector-cybercrime-tracker version 5.11.11 on Docker hub

### ISSUE THREAD

**Issue by Tonnulus** [OpenCTI-Platform/connectors#1508]
## Prerequisites

- [X] I read the [Deployment and Setup](https://filigran.notion.site/OpenCTI-Public-Knowledge-Base-d411e5e477734c59887dad3649f20518) section of the OpenCTI documentation as well as the [Troubleshooting](https://filigran.notion.site/Troubleshooting-ebc8fb04137d495aad917bc20340b9a6) page and didn't find anything relevant to my problem.
- [X] I went through old GitHub issues and couldn't find anything relevant
- [X] I googled the issue and didn't find anything relevant

## Description

On Docker hub  I can not find container with the tag 5.11.11 for connector-cryptolaemus and connector-cybercrime-tracker.

Why the last tag is 5.10.3, rolling or lastest for connector-cryptolaemus and 5.10.4 for connector-cybercrime-tracker ? 

## Environment

- https://hub.docker.com/r/opencti/connector-cryptolaemus/tags
- https://hub.docker.com/r/opencti/connector-cybercrime-tracker/tags

**Comment by SamuelHassine** [comment]
Those connectors have been deprecated as the underlying services are down and not updated anymore since more than 1 year.

**Comment by Tonnulus** [comment]
Thank you for this very fast answer
